/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTimetableIndexRouteImport } from './routes/_authenticated/timetable/index'
import { Route as AuthenticatedRoomsIndexRouteImport } from './routes/_authenticated/rooms/index'
import { Route as AuthenticatedMessagesIndexRouteImport } from './routes/_authenticated/messages/index'
import { Route as AuthenticatedExcusesIndexRouteImport } from './routes/_authenticated/excuses/index'
import { Route as AuthenticatedTeacherSubstitutionsRouteImport } from './routes/_authenticated/teacher/substitutions'
import { Route as AuthenticatedStatisticsAbsenceRouteImport } from './routes/_authenticated/statistics/absence'
import { Route as AuthenticatedMessagesConversationIdRouteImport } from './routes/_authenticated/messages/$conversationId'
import { Route as AuthenticatedClassbookLessonIdRouteImport } from './routes/_authenticated/classbook/$lessonId'
import { Route as AuthenticatedAdminTimetableHistoryRouteImport } from './routes/_authenticated/admin/timetable-history'
import { Route as AuthenticatedAdminTimetableEditRouteImport } from './routes/_authenticated/admin/timetable-edit'
import { Route as AuthenticatedAdminSubstitutionsRouteImport } from './routes/_authenticated/admin/substitutions'
import { Route as AuthenticatedAdminSolverRouteImport } from './routes/_authenticated/admin/solver'
import { Route as AuthenticatedAdminResourcesRouteImport } from './routes/_authenticated/admin/resources'
import { Route as AuthenticatedAdminImportRouteImport } from './routes/_authenticated/admin/import'
import { Route as AuthenticatedAdminTeachersIndexRouteImport } from './routes/_authenticated/admin/teachers.index'
import { Route as AuthenticatedAdminSubjectsIndexRouteImport } from './routes/_authenticated/admin/subjects.index'
import { Route as AuthenticatedAdminStudentsIndexRouteImport } from './routes/_authenticated/admin/students.index'
import { Route as AuthenticatedAdminTeachersTeacherIdRouteImport } from './routes/_authenticated/admin/teachers.$teacherId'
import { Route as AuthenticatedAdminStudentsStudentIdRouteImport } from './routes/_authenticated/admin/students.$studentId'
import { Route as AuthenticatedAdminSchoolSettingsRouteImport } from './routes/_authenticated/admin/school.settings'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTimetableIndexRoute =
  AuthenticatedTimetableIndexRouteImport.update({
    id: '/timetable/',
    path: '/timetable/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRoomsIndexRoute = AuthenticatedRoomsIndexRouteImport.update({
  id: '/rooms/',
  path: '/rooms/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMessagesIndexRoute =
  AuthenticatedMessagesIndexRouteImport.update({
    id: '/messages/',
    path: '/messages/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExcusesIndexRoute =
  AuthenticatedExcusesIndexRouteImport.update({
    id: '/excuses/',
    path: '/excuses/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTeacherSubstitutionsRoute =
  AuthenticatedTeacherSubstitutionsRouteImport.update({
    id: '/teacher/substitutions',
    path: '/teacher/substitutions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStatisticsAbsenceRoute =
  AuthenticatedStatisticsAbsenceRouteImport.update({
    id: '/statistics/absence',
    path: '/statistics/absence',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMessagesConversationIdRoute =
  AuthenticatedMessagesConversationIdRouteImport.update({
    id: '/messages/$conversationId',
    path: '/messages/$conversationId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClassbookLessonIdRoute =
  AuthenticatedClassbookLessonIdRouteImport.update({
    id: '/classbook/$lessonId',
    path: '/classbook/$lessonId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminTimetableHistoryRoute =
  AuthenticatedAdminTimetableHistoryRouteImport.update({
    id: '/admin/timetable-history',
    path: '/admin/timetable-history',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminTimetableEditRoute =
  AuthenticatedAdminTimetableEditRouteImport.update({
    id: '/admin/timetable-edit',
    path: '/admin/timetable-edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminSubstitutionsRoute =
  AuthenticatedAdminSubstitutionsRouteImport.update({
    id: '/admin/substitutions',
    path: '/admin/substitutions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminSolverRoute =
  AuthenticatedAdminSolverRouteImport.update({
    id: '/admin/solver',
    path: '/admin/solver',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminResourcesRoute =
  AuthenticatedAdminResourcesRouteImport.update({
    id: '/admin/resources',
    path: '/admin/resources',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminImportRoute =
  AuthenticatedAdminImportRouteImport.update({
    id: '/admin/import',
    path: '/admin/import',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminTeachersIndexRoute =
  AuthenticatedAdminTeachersIndexRouteImport.update({
    id: '/admin/teachers/',
    path: '/admin/teachers/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminSubjectsIndexRoute =
  AuthenticatedAdminSubjectsIndexRouteImport.update({
    id: '/admin/subjects/',
    path: '/admin/subjects/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminStudentsIndexRoute =
  AuthenticatedAdminStudentsIndexRouteImport.update({
    id: '/admin/students/',
    path: '/admin/students/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminTeachersTeacherIdRoute =
  AuthenticatedAdminTeachersTeacherIdRouteImport.update({
    id: '/admin/teachers/$teacherId',
    path: '/admin/teachers/$teacherId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminStudentsStudentIdRoute =
  AuthenticatedAdminStudentsStudentIdRouteImport.update({
    id: '/admin/students/$studentId',
    path: '/admin/students/$studentId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminSchoolSettingsRoute =
  AuthenticatedAdminSchoolSettingsRouteImport.update({
    id: '/admin/school/settings',
    path: '/admin/school/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/admin/resources': typeof AuthenticatedAdminResourcesRoute
  '/admin/solver': typeof AuthenticatedAdminSolverRoute
  '/admin/substitutions': typeof AuthenticatedAdminSubstitutionsRoute
  '/admin/timetable-edit': typeof AuthenticatedAdminTimetableEditRoute
  '/admin/timetable-history': typeof AuthenticatedAdminTimetableHistoryRoute
  '/classbook/$lessonId': typeof AuthenticatedClassbookLessonIdRoute
  '/messages/$conversationId': typeof AuthenticatedMessagesConversationIdRoute
  '/statistics/absence': typeof AuthenticatedStatisticsAbsenceRoute
  '/teacher/substitutions': typeof AuthenticatedTeacherSubstitutionsRoute
  '/excuses/': typeof AuthenticatedExcusesIndexRoute
  '/messages/': typeof AuthenticatedMessagesIndexRoute
  '/rooms/': typeof AuthenticatedRoomsIndexRoute
  '/timetable/': typeof AuthenticatedTimetableIndexRoute
  '/admin/school/settings': typeof AuthenticatedAdminSchoolSettingsRoute
  '/admin/students/$studentId': typeof AuthenticatedAdminStudentsStudentIdRoute
  '/admin/teachers/$teacherId': typeof AuthenticatedAdminTeachersTeacherIdRoute
  '/admin/students/': typeof AuthenticatedAdminStudentsIndexRoute
  '/admin/subjects/': typeof AuthenticatedAdminSubjectsIndexRoute
  '/admin/teachers/': typeof AuthenticatedAdminTeachersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/admin/resources': typeof AuthenticatedAdminResourcesRoute
  '/admin/solver': typeof AuthenticatedAdminSolverRoute
  '/admin/substitutions': typeof AuthenticatedAdminSubstitutionsRoute
  '/admin/timetable-edit': typeof AuthenticatedAdminTimetableEditRoute
  '/admin/timetable-history': typeof AuthenticatedAdminTimetableHistoryRoute
  '/classbook/$lessonId': typeof AuthenticatedClassbookLessonIdRoute
  '/messages/$conversationId': typeof AuthenticatedMessagesConversationIdRoute
  '/statistics/absence': typeof AuthenticatedStatisticsAbsenceRoute
  '/teacher/substitutions': typeof AuthenticatedTeacherSubstitutionsRoute
  '/excuses': typeof AuthenticatedExcusesIndexRoute
  '/messages': typeof AuthenticatedMessagesIndexRoute
  '/rooms': typeof AuthenticatedRoomsIndexRoute
  '/timetable': typeof AuthenticatedTimetableIndexRoute
  '/admin/school/settings': typeof AuthenticatedAdminSchoolSettingsRoute
  '/admin/students/$studentId': typeof AuthenticatedAdminStudentsStudentIdRoute
  '/admin/teachers/$teacherId': typeof AuthenticatedAdminTeachersTeacherIdRoute
  '/admin/students': typeof AuthenticatedAdminStudentsIndexRoute
  '/admin/subjects': typeof AuthenticatedAdminSubjectsIndexRoute
  '/admin/teachers': typeof AuthenticatedAdminTeachersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/admin/import': typeof AuthenticatedAdminImportRoute
  '/_authenticated/admin/resources': typeof AuthenticatedAdminResourcesRoute
  '/_authenticated/admin/solver': typeof AuthenticatedAdminSolverRoute
  '/_authenticated/admin/substitutions': typeof AuthenticatedAdminSubstitutionsRoute
  '/_authenticated/admin/timetable-edit': typeof AuthenticatedAdminTimetableEditRoute
  '/_authenticated/admin/timetable-history': typeof AuthenticatedAdminTimetableHistoryRoute
  '/_authenticated/classbook/$lessonId': typeof AuthenticatedClassbookLessonIdRoute
  '/_authenticated/messages/$conversationId': typeof AuthenticatedMessagesConversationIdRoute
  '/_authenticated/statistics/absence': typeof AuthenticatedStatisticsAbsenceRoute
  '/_authenticated/teacher/substitutions': typeof AuthenticatedTeacherSubstitutionsRoute
  '/_authenticated/excuses/': typeof AuthenticatedExcusesIndexRoute
  '/_authenticated/messages/': typeof AuthenticatedMessagesIndexRoute
  '/_authenticated/rooms/': typeof AuthenticatedRoomsIndexRoute
  '/_authenticated/timetable/': typeof AuthenticatedTimetableIndexRoute
  '/_authenticated/admin/school/settings': typeof AuthenticatedAdminSchoolSettingsRoute
  '/_authenticated/admin/students/$studentId': typeof AuthenticatedAdminStudentsStudentIdRoute
  '/_authenticated/admin/teachers/$teacherId': typeof AuthenticatedAdminTeachersTeacherIdRoute
  '/_authenticated/admin/students/': typeof AuthenticatedAdminStudentsIndexRoute
  '/_authenticated/admin/subjects/': typeof AuthenticatedAdminSubjectsIndexRoute
  '/_authenticated/admin/teachers/': typeof AuthenticatedAdminTeachersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/admin/import'
    | '/admin/resources'
    | '/admin/solver'
    | '/admin/substitutions'
    | '/admin/timetable-edit'
    | '/admin/timetable-history'
    | '/classbook/$lessonId'
    | '/messages/$conversationId'
    | '/statistics/absence'
    | '/teacher/substitutions'
    | '/excuses/'
    | '/messages/'
    | '/rooms/'
    | '/timetable/'
    | '/admin/school/settings'
    | '/admin/students/$studentId'
    | '/admin/teachers/$teacherId'
    | '/admin/students/'
    | '/admin/subjects/'
    | '/admin/teachers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/admin/import'
    | '/admin/resources'
    | '/admin/solver'
    | '/admin/substitutions'
    | '/admin/timetable-edit'
    | '/admin/timetable-history'
    | '/classbook/$lessonId'
    | '/messages/$conversationId'
    | '/statistics/absence'
    | '/teacher/substitutions'
    | '/excuses'
    | '/messages'
    | '/rooms'
    | '/timetable'
    | '/admin/school/settings'
    | '/admin/students/$studentId'
    | '/admin/teachers/$teacherId'
    | '/admin/students'
    | '/admin/subjects'
    | '/admin/teachers'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/settings'
    | '/_authenticated/admin/import'
    | '/_authenticated/admin/resources'
    | '/_authenticated/admin/solver'
    | '/_authenticated/admin/substitutions'
    | '/_authenticated/admin/timetable-edit'
    | '/_authenticated/admin/timetable-history'
    | '/_authenticated/classbook/$lessonId'
    | '/_authenticated/messages/$conversationId'
    | '/_authenticated/statistics/absence'
    | '/_authenticated/teacher/substitutions'
    | '/_authenticated/excuses/'
    | '/_authenticated/messages/'
    | '/_authenticated/rooms/'
    | '/_authenticated/timetable/'
    | '/_authenticated/admin/school/settings'
    | '/_authenticated/admin/students/$studentId'
    | '/_authenticated/admin/teachers/$teacherId'
    | '/_authenticated/admin/students/'
    | '/_authenticated/admin/subjects/'
    | '/_authenticated/admin/teachers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/timetable/': {
      id: '/_authenticated/timetable/'
      path: '/timetable'
      fullPath: '/timetable/'
      preLoaderRoute: typeof AuthenticatedTimetableIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rooms/': {
      id: '/_authenticated/rooms/'
      path: '/rooms'
      fullPath: '/rooms/'
      preLoaderRoute: typeof AuthenticatedRoomsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/messages/': {
      id: '/_authenticated/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof AuthenticatedMessagesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/excuses/': {
      id: '/_authenticated/excuses/'
      path: '/excuses'
      fullPath: '/excuses/'
      preLoaderRoute: typeof AuthenticatedExcusesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/teacher/substitutions': {
      id: '/_authenticated/teacher/substitutions'
      path: '/teacher/substitutions'
      fullPath: '/teacher/substitutions'
      preLoaderRoute: typeof AuthenticatedTeacherSubstitutionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/statistics/absence': {
      id: '/_authenticated/statistics/absence'
      path: '/statistics/absence'
      fullPath: '/statistics/absence'
      preLoaderRoute: typeof AuthenticatedStatisticsAbsenceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/messages/$conversationId': {
      id: '/_authenticated/messages/$conversationId'
      path: '/messages/$conversationId'
      fullPath: '/messages/$conversationId'
      preLoaderRoute: typeof AuthenticatedMessagesConversationIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/classbook/$lessonId': {
      id: '/_authenticated/classbook/$lessonId'
      path: '/classbook/$lessonId'
      fullPath: '/classbook/$lessonId'
      preLoaderRoute: typeof AuthenticatedClassbookLessonIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/timetable-history': {
      id: '/_authenticated/admin/timetable-history'
      path: '/admin/timetable-history'
      fullPath: '/admin/timetable-history'
      preLoaderRoute: typeof AuthenticatedAdminTimetableHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/timetable-edit': {
      id: '/_authenticated/admin/timetable-edit'
      path: '/admin/timetable-edit'
      fullPath: '/admin/timetable-edit'
      preLoaderRoute: typeof AuthenticatedAdminTimetableEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/substitutions': {
      id: '/_authenticated/admin/substitutions'
      path: '/admin/substitutions'
      fullPath: '/admin/substitutions'
      preLoaderRoute: typeof AuthenticatedAdminSubstitutionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/solver': {
      id: '/_authenticated/admin/solver'
      path: '/admin/solver'
      fullPath: '/admin/solver'
      preLoaderRoute: typeof AuthenticatedAdminSolverRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/resources': {
      id: '/_authenticated/admin/resources'
      path: '/admin/resources'
      fullPath: '/admin/resources'
      preLoaderRoute: typeof AuthenticatedAdminResourcesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/import': {
      id: '/_authenticated/admin/import'
      path: '/admin/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AuthenticatedAdminImportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/teachers/': {
      id: '/_authenticated/admin/teachers/'
      path: '/admin/teachers'
      fullPath: '/admin/teachers/'
      preLoaderRoute: typeof AuthenticatedAdminTeachersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/subjects/': {
      id: '/_authenticated/admin/subjects/'
      path: '/admin/subjects'
      fullPath: '/admin/subjects/'
      preLoaderRoute: typeof AuthenticatedAdminSubjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/students/': {
      id: '/_authenticated/admin/students/'
      path: '/admin/students'
      fullPath: '/admin/students/'
      preLoaderRoute: typeof AuthenticatedAdminStudentsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/teachers/$teacherId': {
      id: '/_authenticated/admin/teachers/$teacherId'
      path: '/admin/teachers/$teacherId'
      fullPath: '/admin/teachers/$teacherId'
      preLoaderRoute: typeof AuthenticatedAdminTeachersTeacherIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/students/$studentId': {
      id: '/_authenticated/admin/students/$studentId'
      path: '/admin/students/$studentId'
      fullPath: '/admin/students/$studentId'
      preLoaderRoute: typeof AuthenticatedAdminStudentsStudentIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/school/settings': {
      id: '/_authenticated/admin/school/settings'
      path: '/admin/school/settings'
      fullPath: '/admin/school/settings'
      preLoaderRoute: typeof AuthenticatedAdminSchoolSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedAdminImportRoute: typeof AuthenticatedAdminImportRoute
  AuthenticatedAdminResourcesRoute: typeof AuthenticatedAdminResourcesRoute
  AuthenticatedAdminSolverRoute: typeof AuthenticatedAdminSolverRoute
  AuthenticatedAdminSubstitutionsRoute: typeof AuthenticatedAdminSubstitutionsRoute
  AuthenticatedAdminTimetableEditRoute: typeof AuthenticatedAdminTimetableEditRoute
  AuthenticatedAdminTimetableHistoryRoute: typeof AuthenticatedAdminTimetableHistoryRoute
  AuthenticatedClassbookLessonIdRoute: typeof AuthenticatedClassbookLessonIdRoute
  AuthenticatedMessagesConversationIdRoute: typeof AuthenticatedMessagesConversationIdRoute
  AuthenticatedStatisticsAbsenceRoute: typeof AuthenticatedStatisticsAbsenceRoute
  AuthenticatedTeacherSubstitutionsRoute: typeof AuthenticatedTeacherSubstitutionsRoute
  AuthenticatedExcusesIndexRoute: typeof AuthenticatedExcusesIndexRoute
  AuthenticatedMessagesIndexRoute: typeof AuthenticatedMessagesIndexRoute
  AuthenticatedRoomsIndexRoute: typeof AuthenticatedRoomsIndexRoute
  AuthenticatedTimetableIndexRoute: typeof AuthenticatedTimetableIndexRoute
  AuthenticatedAdminSchoolSettingsRoute: typeof AuthenticatedAdminSchoolSettingsRoute
  AuthenticatedAdminStudentsStudentIdRoute: typeof AuthenticatedAdminStudentsStudentIdRoute
  AuthenticatedAdminTeachersTeacherIdRoute: typeof AuthenticatedAdminTeachersTeacherIdRoute
  AuthenticatedAdminStudentsIndexRoute: typeof AuthenticatedAdminStudentsIndexRoute
  AuthenticatedAdminSubjectsIndexRoute: typeof AuthenticatedAdminSubjectsIndexRoute
  AuthenticatedAdminTeachersIndexRoute: typeof AuthenticatedAdminTeachersIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedAdminImportRoute: AuthenticatedAdminImportRoute,
  AuthenticatedAdminResourcesRoute: AuthenticatedAdminResourcesRoute,
  AuthenticatedAdminSolverRoute: AuthenticatedAdminSolverRoute,
  AuthenticatedAdminSubstitutionsRoute: AuthenticatedAdminSubstitutionsRoute,
  AuthenticatedAdminTimetableEditRoute: AuthenticatedAdminTimetableEditRoute,
  AuthenticatedAdminTimetableHistoryRoute:
    AuthenticatedAdminTimetableHistoryRoute,
  AuthenticatedClassbookLessonIdRoute: AuthenticatedClassbookLessonIdRoute,
  AuthenticatedMessagesConversationIdRoute:
    AuthenticatedMessagesConversationIdRoute,
  AuthenticatedStatisticsAbsenceRoute: AuthenticatedStatisticsAbsenceRoute,
  AuthenticatedTeacherSubstitutionsRoute:
    AuthenticatedTeacherSubstitutionsRoute,
  AuthenticatedExcusesIndexRoute: AuthenticatedExcusesIndexRoute,
  AuthenticatedMessagesIndexRoute: AuthenticatedMessagesIndexRoute,
  AuthenticatedRoomsIndexRoute: AuthenticatedRoomsIndexRoute,
  AuthenticatedTimetableIndexRoute: AuthenticatedTimetableIndexRoute,
  AuthenticatedAdminSchoolSettingsRoute: AuthenticatedAdminSchoolSettingsRoute,
  AuthenticatedAdminStudentsStudentIdRoute:
    AuthenticatedAdminStudentsStudentIdRoute,
  AuthenticatedAdminTeachersTeacherIdRoute:
    AuthenticatedAdminTeachersTeacherIdRoute,
  AuthenticatedAdminStudentsIndexRoute: AuthenticatedAdminStudentsIndexRoute,
  AuthenticatedAdminSubjectsIndexRoute: AuthenticatedAdminSubjectsIndexRoute,
  AuthenticatedAdminTeachersIndexRoute: AuthenticatedAdminTeachersIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
